import { test, after } from "node:test";
import assert from "node:assert/strict";
import { prisma } from "../src/lib/prisma";
import { limit, jsonBody, sameOrigin, SafeError } from "../src/lib/security";
import { fulfillCheckout, reviewPayment, entitled } from "../src/lib/payments";
import { getStripe } from "../src/lib/stripe";
import { ticketSchema } from "../src/lib/validation";
import { validateFile } from "../src/lib/upload-validation";
import sharp from "sharp";
import type Stripe from "stripe";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
after(()=>prisma.$disconnect());
test("production has no password provider; revoked, disabled and stale admin sessions fail closed",async()=>{
  let config: {providers:unknown[];callbacks:{jwt:(args:Record<string,unknown>)=>Promise<unknown>}};
  let user={sessionVersion:2,disabledAt:null as Date|null,email:"admin@example.invalid",name:"Admin"};
  const mocks:Record<string,unknown>={"next-auth":(c:typeof config)=>{config=c;return{}},"next-auth/providers/google":()=>({provider:"google"}),"next-auth/providers/credentials":()=>({provider:"credentials"}),"bcryptjs":{compare:()=>true},"zod":{z:{}},"@/lib/prisma":{prisma:{user:{findUnique:async()=>user}}},"@/lib/security":{clientIp:()=>"local",limit:async()=>{}}};
  const code=ts.transpileModule(fs.readFileSync("src/auth.ts","utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
  vm.runInNewContext(code,{exports:{},require:(name:string)=>mocks[name],process:{env:{NODE_ENV:"production",AUTH_GOOGLE_ID:"test",AUTH_GOOGLE_SECRET:"test",ADMIN_EMAIL:"admin@example.invalid"}},Date});
  assert.equal(config!.providers.length,1);
  const token={id:"test",sessionVersion:2,authenticatedAt:Date.now()};
  assert.ok(await config!.callbacks.jwt({token:{...token}}));
  assert.equal(await config!.callbacks.jwt({token:{...token,sessionVersion:1}}),null);
  assert.equal(await config!.callbacks.jwt({token:{...token,authenticatedAt:Date.now()-9*3600000}}),null);
  user={...user,disabledAt:new Date()};assert.equal(await config!.callbacks.jwt({token:{...token}}),null);
});
let seq=0;
async function fixture(type="LAUNCH",step=6){const id=String(++seq);const user=await prisma.user.create({data:{name:"Test",email:id+"@example.invalid"}});const ticket=await prisma.ticket.create({data:{userId:user.id,package:"starter",step,businessName:"Test",ownerName:"Test",quotedPrice:50000,status:"IN_PROGRESS",quoteType:type==="AI_QUOTE"?"AI":"FREE"}});const p=await prisma.payment.create({data:{ticketId:ticket.id,type,amount:type==="AI_QUOTE"?500:15000,stripeSessionId:"cs_"+id,checkoutKey:ticket.id+":"+type}});const checkout={id:p.stripeSessionId,payment_status:"paid",mode:"payment",amount_total:p.amount,currency:"usd",payment_intent:"pi_"+id,metadata:{paymentId:p.id,ticketId:ticket.id,paymentType:type}} as unknown as Stripe.Checkout.Session;return {ticket,p,checkout};}
test("payments remain off without explicit configuration",()=>{assert.equal(getStripe(),null)});
test("unpaid completion cannot mark paid or advance",async()=>{const f=await fixture();f.checkout.payment_status="unpaid";await fulfillCheckout(f.checkout,"evt_unpaid","checkout.session.completed");assert.equal((await prisma.payment.findUniqueOrThrow({where:{id:f.p.id}})).status,"PENDING");assert.equal((await prisma.ticket.findUniqueOrThrow({where:{id:f.ticket.id}})).step,6)});
test("amount, currency, metadata and missing records are rejected",async()=>{const f=await fixture();for(const bad of [{amount_total:1},{currency:"eur"},{metadata:{...f.checkout.metadata,paymentId:"wrong"}},{id:"unknown"}])await assert.rejects(fulfillCheckout({...f.checkout,...bad} as Stripe.Checkout.Session,"evt_mismatch","checkout.session.completed"));assert.equal((await prisma.payment.findUniqueOrThrow({where:{id:f.p.id}})).status,"PENDING")});
test("duplicate and out of order events never regress a project",async()=>{const f=await fixture("DEPOSIT",7);await fulfillCheckout(f.checkout,"evt_late","checkout.session.completed");await fulfillCheckout(f.checkout,"evt_late","checkout.session.completed");await fulfillCheckout(f.checkout,"evt_late_again","checkout.session.completed");assert.equal((await prisma.ticket.findUniqueOrThrow({where:{id:f.ticket.id}})).step,7);assert.equal(await prisma.auditEvent.count({where:{ticketId:f.ticket.id,action:"PAYMENT_SETTLED"}}),1)});
test("repeated AI events never extend chat",async()=>{const f=await fixture("AI_QUOTE",1);await fulfillCheckout(f.checkout,"evt_ai","checkout.session.completed");const first=await prisma.ticket.findUniqueOrThrow({where:{id:f.ticket.id}});await fulfillCheckout(f.checkout,"evt_ai_2","checkout.session.completed");assert.equal((await prisma.ticket.findUniqueOrThrow({where:{id:f.ticket.id}})).aiChatExpiresAt?.getTime(),first.aiChatExpiresAt?.getTime())});
test("refund freezes entitlement and duplicate handling stays safe",async()=>{const f=await fixture();await fulfillCheckout(f.checkout,"evt_pay","checkout.session.completed");await reviewPayment(String(f.checkout.payment_intent),"evt_refund","charge.refunded","REFUNDED");await fulfillCheckout(f.checkout,"evt_old","checkout.session.completed");const ticket=await prisma.ticket.findUniqueOrThrow({where:{id:f.ticket.id},include:{payments:true}});assert.equal(ticket.status,"PAYMENT_REVIEW");assert.equal(entitled(ticket),false)});
test("zero/partial launch entries cannot unlock source",()=>{assert.equal(entitled({package:"starter",status:"LAUNCHED",quotedPrice:50000,payments:[{type:"LAUNCH",status:"PAID",amount:0}]}),false);assert.equal(entitled({package:"proto-code",status:"PAID",quotedPrice:10000,payments:[{type:"FULL",status:"PAID",amount:10000}]}),true)});
test("distributed quota rejects over-limit requests without storing IPs",async()=>{const rule={scope:"test",subject:"sensitive-ip",max:2,seconds:60};await limit([rule]);await limit([rule]);await assert.rejects(limit([rule]),(e:unknown)=>e instanceof SafeError&&e.status===429);const rows=await prisma.rateLimit.findMany();assert.ok(rows.every(r=>!r.id.includes("sensitive")))});
test("cross-origin and oversized/malformed bodies are rejected",async()=>{assert.throws(()=>sameOrigin(new Request("https://ibq.invalid/api",{headers:{origin:"https://evil.invalid"}})));await assert.rejects(jsonBody(new Request("https://ibq.invalid",{method:"POST",headers:{"content-type":"application/json"},body:"x"})));await assert.rejects(jsonBody(new Request("https://ibq.invalid",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:"x".repeat(40000)})})));});
test("ticket fields and URLs have server-side limits",()=>{assert.equal(ticketSchema.safeParse({package:"starter",businessName:"XX",ownerName:"YY",notes:"x".repeat(4001)}).success,false);assert.equal(ticketSchema.safeParse({package:"starter",businessName:"XX",ownerName:"YY",logoUrl:"javascript:alert(1)"}).success,false)});
test("spoofed images are rejected; real images are re-encoded",async()=>{await assert.rejects(validateFile(new File(["<script>bad</script>"],"x.png",{type:"image/png"}),true));const png=await sharp({create:{width:20,height:20,channels:3,background:"#3dffc8"}}).png().toBuffer();const result=await validateFile(new File([new Uint8Array(png)],"x.png",{type:"image/png"}),true);assert.equal(result.file.type,"image/webp");assert.equal(result.extension,"webp")});
