import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { getStripe } from "@/lib/stripe";
import { AIChat } from "@/components/ai-chat";
import { SiteHeader } from "@/components/site-header";
export const metadata:Metadata={title:"AI quote chat"};
export default async function AiQuote({searchParams}:{searchParams:Promise<{ticket?:string;session_id?:string}>}){const session=await auth();if(!session?.user?.id)redirect("/login");const q=await searchParams;if(!q.ticket)redirect("/quote");let ticket=await prisma.ticket.findFirst({where:{id:q.ticket,userId:session.user.id},include:{payments:true}});if(!ticket)redirect("/quote");if(q.session_id&&!ticket.payments.some(p=>p.status==="PAID")){const stripe=getStripe();if(stripe){const checkout=await stripe.checkout.sessions.retrieve(q.session_id);if(checkout.payment_status==="paid"&&checkout.metadata?.ticketId===ticket.id){const now=new Date();await prisma.payment.updateMany({where:{stripeSessionId:q.session_id},data:{status:"PAID"}});ticket=await prisma.ticket.update({where:{id:ticket.id},data:{status:"AI_ACTIVE",aiChatStartedAt:now,aiChatExpiresAt:new Date(now.getTime()+300000)},include:{payments:true}});}}}if(!ticket.aiChatExpiresAt)return <><SiteHeader/><main className="shell page-pad"><div className="notice">Payment is processing. Refresh this page in a moment.</div></main></>;const initial=Object.fromEntries(["businessName","ownerName","phone","email","instagram","address","hours","logoUrl","tagline","pages","services","photos","cta","reviews","bookingTypes","availability","stripeScope","customScope","notes"].map(k=>[k,(ticket as unknown as Record<string,string|null>)[k]]));return <><SiteHeader/><main className="shell page-pad"><header className="page-heading"><p className="eyebrow">$5 guided quote</p><h1 className="font-display">Five minutes. <span className="gradient-text">One clear ticket.</span></h1></header><AIChat ticketId={ticket.id} expiresAt={ticket.aiChatExpiresAt.toISOString()} initial={initial} initialSeconds={300}/></main></>}
