"use client";
import { readDraft, clearDraft } from "@/lib/drafts";
import Link from "next/link";
import { useEffect, useState } from "react";
import { UploadCloud } from "lucide-react";

export function PayButton({ticketId,label,amount}:{ticketId:string;label:string;amount:number}){const[busy,setBusy]=useState(false),[error,setError]=useState("");async function pay(){setBusy(true);const r=await fetch("/api/stripe/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"INSTALLMENT",ticketId})});const d=await r.json();if(d.url)location.href=d.url;else{setError(d.error||"Checkout failed.");setBusy(false)}}return <div><button className="btn btn-primary" onClick={pay} disabled={busy}>{busy?"Opening…":`${label} — $${(amount/100).toFixed(2)}`}</button>{error&&<p className="form-error">{error}</p>}</div>}
export function UploadForm({ticketId}:{ticketId:string}){const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const r=await fetch("/api/uploads",{method:"POST",body:new FormData(e.currentTarget)});const d=await r.json();setBusy(false);setMessage(r.ok?"Reference uploaded. Refresh to see it.":d.error)}return <form className="upload-form" onSubmit={upload}><input type="hidden" name="ticketId" value={ticketId}/><label><UploadCloud/>Add reference photos (under 4 MB)<input type="file" name="file" accept="image/jpeg,image/png,image/webp" required/></label><button className="btn btn-secondary" disabled={busy}>{busy?"Uploading…":"Upload"}</button>{message&&<p>{message}</p>}</form>}
export function SavedDraftNotice({userId}:{userId:string}){const[has,setHas]=useState(false);useEffect(()=>{const timer=setTimeout(()=>setHas(!!readDraft(userId)),0);return()=>clearTimeout(timer)},[userId]);if(!has)return null;return <div className="notice">Your quote draft expires after 24 hours or when this tab closes. <Link href="/#intake">Finish and send it.</Link> <button onClick={()=>{clearDraft();setHas(false);}}>Clear draft</button></div>}
