"use client";
import { readDraft, saveDraft, clearDraft } from "@/lib/drafts";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Bot, FilePenLine } from "lucide-react";

export function QuoteForm({authenticated,initialPackage,userId}:{authenticated:boolean;initialPackage:string;userId:string|null}){
  const [mode,setMode]=useState<"free"|"ai">("free"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);const formRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{const draft=readDraft(userId);if(!draft)return;try{const values=draft as Record<string,string|string[]>;for(const [key,value] of Object.entries(values)){const nodes=formRef.current?.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`[name="${CSS.escape(key)}"]`);nodes?.forEach(node=>{if(node instanceof HTMLInputElement&&node.type==="checkbox")node.checked=Array.isArray(value)&&value.includes(node.value);else if(!Array.isArray(value))node.value=value;});}const timer=setTimeout(()=>setMessage(authenticated?"Your saved draft is still here. Review it, then submit when ready.":"Your draft is saved in this tab for up to 24 hours. Sign in to send it."),0);return()=>clearTimeout(timer)}catch{}},[authenticated,userId]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;const form=new FormData(formElement);const data=Object.fromEntries(form.entries()) as Record<string,unknown>;data.pages=form.getAll("pages");saveDraft(data,userId);if(!authenticated){setMessage("Your draft is saved on this device. Sign in or create an account to send it.");return;}setBusy(true);const res=await fetch("/api/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const json=await res.json();setBusy(false);if(!res.ok){setMessage(json.error||"Something went wrong.");return;}clearDraft();setMessage(`Ticket ${json.ticket.id.slice(-6).toUpperCase()} created. Open your account to track it.`);formElement.reset();}
  async function startAi(){if(!authenticated){setMessage("Sign in or create an account first. We will keep your AI quote choice here.");return;}setBusy(true);const res=await fetch("/api/stripe/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"AI_QUOTE",package:initialPackage})});const data=await res.json();setBusy(false);if(data.url)location.href=data.url;else setMessage(data.error||"Could not start checkout.");}
  return <section className="quote-wrap"><div className="quote-tabs" role="tablist"><button className={mode==="free"?"active":""} onClick={()=>setMode("free")} role="tab"><FilePenLine/>Free quote <span>$0</span></button><button className={mode==="ai"?"active":""} onClick={()=>setMode("ai")} role="tab"><Bot/>AI quote <span>$5 / 5 min</span></button></div>
    {message&&<div className="notice" role="status">{message}{!authenticated&&<span><Link href="/signup">Create account</Link> · <Link href="/login">Sign in</Link></span>}</div>}
    {mode==="ai"?<div className="glass-card ai-choice"><p className="eyebrow">Five focused minutes</p><h2 className="font-display">Talk it out. Leave with a clean ticket.</h2><p>The guided chat captures your business, pages, services, photos, calls to action, booking needs, and custom scope. When time expires, the chat locks and your structured ticket is ready to confirm.</p><button className="btn btn-primary" onClick={startAi} disabled={busy}>{busy?"Opening…":"Pay $5 and start"}</button></div>:
    <form ref={formRef} className="quote-form glass-card" onSubmit={submit}><fieldset><legend>01 · The basics</legend><div className="form-grid"><label>Business name<input name="businessName" required minLength={2}/></label><label>Owner name<input name="ownerName" required minLength={2}/></label><label>Phone<input name="phone" type="tel"/></label><label>Email<input name="email" type="email"/></label><label>Instagram<input name="instagram" placeholder="@handle"/></label><label>Address or service area<input name="address"/></label><label className="wide">Hours<textarea name="hours" rows={2}/></label><label>Logo link<input name="logoUrl" type="url" placeholder="https://…"/></label><label>Tagline<input name="tagline"/></label></div></fieldset>
    <fieldset><legend>02 · Package and pages</legend><div className="form-grid"><label>Package<select name="package" defaultValue={initialPackage}><option value="starter">Single Page — $500</option><option value="full-build">Full Website — $999 · 72 hours</option><option value="custom">Custom — from $2,500</option></select></label><div className="wide"><span className="field-label">Pages</span><div className="check-grid">{["Home","Services","Gallery","Contact","Booking if Full Website"].map(x=><label className="check" key={x}><input type="checkbox" name="pages" value={x}/>{x}</label>)}</div></div></div></fieldset>
    <fieldset><legend>03 · What goes on the site</legend><div className="form-grid"><label className="wide">Services — name, price, duration<textarea name="services" rows={4} placeholder="Silk press — $85 — 90 min"/></label><label className="wide">Photos<textarea name="photos" rows={3} placeholder="Hero, work shots, optional team photos"/></label><label>Primary action<select name="cta"><option>Call</option><option>Text</option><option>Book</option></select></label><label>Reviews (optional)<textarea name="reviews" rows={2}/></label></div></fieldset>
    <fieldset><legend>04 · Full Website or Custom</legend><div className="form-grid"><label>Booking types<textarea name="bookingTypes" rows={3}/></label><label>Availability<textarea name="availability" rows={3}/></label><label className="wide">Stripe needs<textarea name="stripeScope" rows={2} placeholder="Cards, Apple Pay, Google Pay"/></label><label className="wide">Custom AI, agent, or feed scope<textarea name="customScope" rows={3} placeholder="Quoted separately"/></label><label className="wide">Anything else?<textarea name="notes" rows={4}/></label></div></fieldset><button className="btn btn-primary submit" disabled={busy}>{busy?"Sending…":"Create my ticket"}</button></form>}
  </section>;
}
